---
title: "ch-analysis"
author: "Aji John"
date: "12/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(ForestGapR)
library(fieldRS)
library(viridis)
library(rasterVis)
library(tidyverse)
```


```{r , echo=FALSE}
start_time <- Sys.time()
  beginCluster()
  
```

```{r cars}
ch_norm <- raster('./data/switzerland_dem_clipped_wgs84_3mnormalized_layers_r2.tiff')
```

## Including Plots

You can also embed plots, for example:

```{r, echo=FALSE}
prediction_SWiss <- raster('./data/pred_merged_UTM_3m_s1_nodata_ch_r1.tif')
```

```{r, echo=FALSE}
prediction_SWiss <- raster('./data/pred_merged_wgs84_3m_s1_nodata_ch_r1.tif')
```

```{r, echo=FALSE}
aso_SWiss <- raster('./data/EUCHDB20170517_SUPERsnow_depth_3m_binary_wgs84_3m.tif')

cropped_aso_swiss <- crop(aso_SWiss, extent(prediction_SWiss))

```

```{r, echo=FALSE}
planet_img_swiss_stack <-raster::stack('data/20170516_092458_1030_3B_AnalyticMS_SR_clip.tif')
planet_img_swiss_stack <- planet_img_swiss_stack/10000
```



```{r, echo=FALSE}
# Vector of correspondence
cols.nb <- c("0" = "blue", "1" = "red")

gplot(prediction_SWiss) + 
  geom_tile(aes(fill = as.character(value)) ) +
 viridis::scale_fill_viridis(direction = -1,discrete=TRUE,begin=0,end=1, na.value='#FFFFFF00') + 
  theme_bw() +
theme(panel.background = element_rect(colour = "black", fill="lightblue")) 
```

```{r, echo=FALSE}
# Vector of correspondence
cols.nb <- c("0" = "blue", "1" = "red")
library(patchwork)
plotma <- gplot(prediction_SWiss) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
theme(panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom",
      axis.text.x = element_text(angle = 45, hjust = 1)) +
ggspatial::annotation_scale(location = "tr", width_hint = 0.2) +
    ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
       pad_y = unit(0.2, "mm"),style = ggspatial::north_arrow_fancy_orienteering) +
  labs(x='',  y='') 


plotmb <- gplot(cropped_aso_swiss) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
  #theme_bw()+
theme(panel.background = element_rect(colour = "black", fill="white"),legend.position = "none",
      axis.text.x = element_text(angle = 45, hjust = 1)) +
ggspatial::annotation_scale(location = "tr", width_hint = 0.2) +
    ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
       pad_y = unit(0.2, "mm"),style = ggspatial::north_arrow_fancy_orienteering) +
  labs(x='',  y='') 


```



```{r , echo=FALSE}
library('ceramic')

data("wrld_simpl", package = "maptools")
#im <- cc_location(cbind( -107.1661, 38.81874 ), buffer = 1e5, ype = "mapbox.satellite")

im_swiss_site <- cc_location(extent(cropped_aso_swiss), buffer = 1e5, ype = "mapbox.satellite")
#im <- cc_location(p, ype = "mapbox.terrain-rgb")

#raster::writeRaster(im_swiss_site,'data/swiss-_aoi.tiff',overwrite=TRUE)
#> Preparing to download: 12 tiles at zoom = 6 from 
#> https://api.mapbox.com/v4/mapbox.light/
raster::plotRGB(im_swiss_site)
```



```{r , echo=FALSE}
aoi <- extent(c(10.02339, 10.04452, 46.5633, 46.58303 ))

poly_study <- as(aoi,'SpatialPolygons')

poly_study <- fortify(poly_study)
```

```{r , echo=FALSE}
aoi_SWiss <- raster::stack('./data/swiss-_aoi_wgs84.tif')


plotmc <- RStoolbox::ggRGB(aoi_SWiss)+
    coord_sf(crs = 4326)+
theme(panel.background = element_rect(colour = "black", fill="white"),
      axis.text.x = element_text(angle = 45, hjust = 1)) +
ggspatial::annotation_scale(location = "bl", width_hint = 0.5) +
    ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
       pad_y = unit(0.2, "mm"),style = ggspatial::north_arrow_fancy_orienteering) +
  geom_polygon(aes(long,lat), alpha = 0.2, color='green',data = poly_study) +
# coord_equal() +
  labs(x='',  y='') 

```

Area of the study
```{r , echo=FALSE}
library(patchwork)
layout <- "
ABC
"
 plotmc + plotmb + plotma  +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = 'A', title = '',
  subtitle = '',
  caption = 'Mapbox (C)') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("figs/swiss_all_ms.png",dpi=300, dev='png',  height=6, width=10,units="in")
```

```{r , echo=FALSE}
library(RColorBrewer)
cur_col <- brewer.pal(11, "Paired") 
plottest <- gplot(im_swiss_site) + 
   geom_raster(aes(x=x,y=y,fill=value))+
   coord_sf(crs = 4326)+
  #scale_fill_manual(values = cols.nb,
  #                  breaks = 0:1,
  #                  labels = c("No snow", "Snow"),
  #                  name = "") +
 scale_fill_viridis(option="viridis")+
  #theme_bw()+
theme(panel.background = element_rect(colour = "black", fill="white")) +
ggspatial::annotation_scale(location = "bl", width_hint = 0.5) +
    ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
       pad_y = unit(0.2, "in"),style = ggspatial::north_arrow_fancy_orienteering) +
  labs(x='',  y='') 
``` 
 
```{r , echo=FALSE}
 
plotc <-  RStoolbox::ggRGB(im_swiss_site)+
theme(panel.background = element_rect(colour = "black", fill="white")) +
ggspatial::annotation_scale(location = "bl", width_hint = 0.5) +
    ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
       pad_y = unit(0.2, "mm"),style = ggspatial::north_arrow_fancy_orienteering) +
  labs(x='',  y='') 
```


```{r , echo=FALSE}
(plota + plotb ) + plot_layout(guides = 'collect') + 
  plot_annotation(tag_levels = 'A')
ggsave("figs/swiss_asopluspred.png",dpi=300,height=10,width=10,units="in")

```


```{r , echo=FALSE}
plotc/ (plota + plotb ) + 
  plot_layout(guides = 'keep') + 
  plot_annotation(tag_levels = 'A')
ggsave("figs/swiss_asopluspred_combined.png",dpi=300,width=200, height=300, units="mm")
```
```{r , echo=FALSE}
library(patchwork)
layout <- "
AAAA
AAAA
BBCC
BBCC
"
plotc + plota + plotb  +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = 'A', title = '',
  subtitle = '',
  caption = 'Mosaic by Mapbox (A)')
ggsave("figs/swiss_asopluspred_combinedr1.png",dpi=300, dev='png',  height=8, width=10,units="in")
```

perf

```{r , echo=FALSE}
aso_ch_rep <- projectRaster(cropped_aso_swiss,prediction_SWiss,method='ngb')
df_ch_stack <- raster::stack(aso_ch_rep,prediction_SWiss)

data_matrix_ch <- rasterToPoints(df_ch_stack)
head(data_matrix_ch)
datafra_comb_ch <- data_matrix_ch %>% as.data.frame()

colnames(datafra_comb_ch) <- c('x','y','aso','pred')

perf<- confusionMatrix(as.factor(datafra_comb_ch$aso), as.factor(datafra_comb_ch$pred),mode = "prec_recall")

perf
```


```{r , echo=FALSE}
endCluster()
end_time <- Sys.time()
end_time - start_time

```
