---
title: "R Notebook - final figures"
output: html_notebook
---

## R Markdown

Read the layer
```{r}
library(raster)
library(tidyverse)

```

get the area

```{r }
library(tidyverse)
plotch_longer_df <- read_csv(file='./data/CHBASENDVIREDO/processed-data.csv')


# Default bar plot
pch<- plotch_longer_df %>% 
ggplot(aes(x=name, y=avg_metric)) + 
  geom_bar(stat="identity",color="black" , 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=avg_metric-se, ymax=avg_metric+se), width=.2,
                 position=position_dodge(.9),color="#7FC97F") +
  theme_minimal(base_size = 18)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = c(.1,.2,.3,.4,.5,.6,.7,.8,.9,1.0))+
  labs(x="",y="")
swiss_plot <- pch

print(pch)
ggsave("figs/all_scenes_ch-base-ndvi.png",dpi=300, dev='png',  height=8, width=10,units="in")

```

```{r , echo=FALSE}

plot_longer_df <- read_csv(file='./data/COBASENDVIREDO/processed-data.csv')

# Default bar plot
p<- plot_longer_df %>% 
ggplot(aes(x=name, y=avg_metric)) + 
  geom_bar(stat="identity",color="black" , 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=avg_metric-se, ymax=avg_metric+se), width=.2,
                 position=position_dodge(.9),color="#7FC97F") +
  theme_minimal(base_size = 18)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
   scale_y_continuous(breaks = c(.1,.2,.3,.4,.5,.6,.7,.8,.9,1.0))+
  labs(x="",y="Value")
plot_gunni <- p

print(p)
ggsave("figs/all_scenes_gunnison_cobasendvi.png",dpi=300, dev='png',  height=8, width=10,units="in")

```



```{r , echo=FALSE}
library(patchwork)
layout <- "
AB
AB"
   
  plot_gunni+ swiss_plot+ 
  plot_layout(design = layout) +
  plot_annotation(tag_levels = 'A', title = '') 
ggsave("figs/metrics.png",dpi=300, dev='png',  height=10, width=12,units="in")
```
