---
title: "R visual Notebook - Whole scene but one final - good"
output: html_notebook
---

```{r }
library(tidyverse)
library(raster)
library(rasterVis)
```

Smaller area

```{r}
# raster::drawExtent()
#class      : Extent 
#xmin       : -107.0606 
#xmax       : -107.0533 
#ymin       : 39.01486 
#ymax       : 39.02562 

#class      : Extent 
#class      : Extent 
#xmin       : -107.0562 
#xmax       : -107.0517 
#ymin       : 39.04438 
#ymax       : 39.04847 

whole_scene_planet_co <- raster::stack('data/20180524_172327_0f51_3B_AnalyticMS_SR_clip_wgs84.tiff')

# Revised 04/7/2022
#aoi_manu <- extent(c(-107.0562 , -107.0517 ,39.04438 ,39.04847 ))
aoi_manu <- extent(c(-107.0786 ,-107.0528 ,39.0447 ,39.06995))
```

#visualize
```{r , echo=FALSE}
library('ceramic')

data("wrld_simpl", package = "maptools")
#im <- cc_location(cbind( -107.1661, 38.81874 ), buffer = 1e5, ype = "mapbox.satellite")

aoip<- cc_location(aoi_manu, buffer = 1e5, ype = "mapbox.satellite")
#im <- cc_location(p, ype = "mapbox.terrain-rgb")
#model_co_large_aoi <- raster::writeRaster(aoip,'data/model_co_large_aoi.tiff',overwrite=TRUE)
# gdalwarp swiss-_aoi.tiff swiss-_aoi_wgs84.tiff -t_srs "+proj=longlat +ellps=WGS84"
#> Preparing to download: 12 tiles at zoom = 6 from 
#> https://api.mapbox.com/v4/mapbox.light/
raster::plotRGB(aoip)
```

```{r}

#aoi_study_CO <-raster::stack('data/model_co_large_aoi_wgs84.tiff')
#plotRGB(aoi_study_CO)
```
Area of the snipped region




Planet Imagery



```{r , echo=FALSE}
ostudyarea_planet_co <- raster::stack('data/20180524_172327_0f51_3B_AnalyticMS_SR_clip_wgs84.tiff')
planet_large_study_area <- crop(ostudyarea_planet_co,aoi_manu)
#plotRGB(planet_large_study_area)
baseplanet_co <-  RStoolbox::ggRGB(planet_large_study_area)+
coord_sf(crs = 4326)+
theme(panel.background = element_rect(colour = "black", fill="white"),legend.position = "none",
       axis.text.x = element_text(angle = 45, hjust = 1)) +
ggspatial::annotation_scale(location = "bl") +
    ggspatial::annotation_north_arrow(location = "br", which_north = "true", height = unit(1.5, "cm"),
      style = ggspatial::north_arrow_fancy_orienteering) +
  labs(x='',  y='') +theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "none", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +  labs(title = "Planet RGB")
```
```{r , echo=FALSE}
writeRaster(planet_large_study_area, 'data/large_studyarea.tif', overwrite=TRUE, options="COMPRESS=LZW")
```

Looks like 10 km2
```{r}

#raster::area(projectRaster(whole_scene_planet_co, crs = "+init=epsg:32631"))
rterra <- terra::rast('data/large_studyarea.tif')
# area for each raster cell
#a <- terra::area(rterra[[1]], sum=FALSE)

# summed area in km2
terra::cellSize(rterra[[1]], unit="km") 

```

```{r , echo=FALSE}
cols.nb <- c("0" = "blue", "1" = "red")
ostudyarea_basechm_co <- raster('data/BASECHMREDOCO/20180524_172327_0f51_3B_AnalyticMS_SR_clip_merged.tif')
pred_study_basechm_co <- crop(ostudyarea_basechm_co,aoi_manu)
plot(pred_study_basechm_co)
basechm_co <- gplot(pred_study_basechm_co) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "none", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +  labs(title  = "BASE+CHM")
```
```{r , echo=FALSE}
ostudyarea_basedem_co <- raster('data/DEMNORMBASEREDO/20180524_172327_0f51_3B_AnalyticMS_SR_clip_merged.tif')
pred_study_basedemco <- crop(ostudyarea_basedem_co,aoi_manu)
plot(pred_study_basedemco)
basedemco <- gplot(pred_study_basedemco) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "none", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())  +  labs(title = "BASE+DEM")
```

```{r , echo=FALSE}
ostudyarea_basendvi_co <- raster('data/COBASENDVIREDO/20180524_172327_0f51_3B_AnalyticMS_SR_clip_merged.tif')
pred_study_basendvi_co <- crop(ostudyarea_basendvi_co,aoi_manu)
plot(pred_study_basendvi_co)
basendvi_co <- gplot(pred_study_basendvi_co) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
theme(text = element_text(size=16), panel.background = element_rect(colour = "black", fill="green"),legend.position = "none", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +  labs(title = "BASE+NDVI")
```
```{r , echo=FALSE}
ostudyarea_baseslaspnorth_co <- raster('data/SLASNORNORMBASEREDOCO/20180524_172327_0f51_3B_AnalyticMS_SR_clip_merged.tif')
pred_study_baseslopaspnorth_co <- crop(ostudyarea_baseslaspnorth_co,aoi_manu)
plot(pred_study_baseslopaspnorth_co)
baseslopspnorth_co <- gplot(pred_study_baseslopaspnorth_co) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
theme(text = element_text(size=16),panel.background = element_rect(colour = "black", fill="white"),legend.position = "none", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +  labs(title = "BASE+Slope+Aspect+\nNorthness")
```

```{r , echo=FALSE}
ostudyarea_basedemplus_co <- raster('data/DEMplusCOPredictions/20180524_172327_0f51_3B_AnalyticMS_SR_clip_merged.tif')
pred_study_basedemplus_co <- crop(ostudyarea_basedemplus_co,aoi_manu)
plot(pred_study_basedemplus_co)
basedemplus_co <- gplot(pred_study_basedemplus_co) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
theme(text = element_text(size=16),panel.background = element_rect(colour = "black", fill="white"),legend.position = "none", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())   +  labs(title = "BASE+DEM+Slope+\nAspect+Northness")
```

```{r , echo=FALSE}
ostudyarea_base_co <- raster('data/COBASE/20180524_172327_0f51_3B_AnalyticMS_SR_clip_merged.tif')
pred_study_base_co <- crop(ostudyarea_base_co,aoi_manu)
plot(pred_study_base_co)
```

```{r , echo=FALSE}
base_co <- gplot(pred_study_base_co) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "none", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +  labs(title = "BASE")
```

```{r , echo=FALSE}
ostudyarea_baseext_co <- raster('data/COLORADOBASEEXT2/20180524_172327_0f51_3B_AnalyticMS_SR_clip_merged.tif')
pred_study_baseext_co <- crop(ostudyarea_baseext_co,aoi_manu)
plot(pred_study_baseext_co)

baseext_co <- gplot(pred_study_baseext_co) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +  labs(title = "BASE")

baseext_co_alt <- gplot(pred_study_baseext_co) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +  labs(title = "")

```


```{r , echo=FALSE}
aso_colorado <- raster('data/ASO_3M_SD_USCOGE_20180524_binary_wgs84.tif')



aso_study_area<- crop(aso_colorado,aoi_manu)
plot(aso_study_area)
```

```{r , echo=FALSE}
base_aso_imagery <- gplot(aso_study_area) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "left", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())   +  labs(title =  "ASO LIDAR SCA")

base_aso_imagery_alt <- gplot(aso_study_area) + 
  geom_tile(aes(fill = as.character(value)) ) +
   coord_sf(crs = 4326)+
  scale_fill_manual(values = cols.nb,
                    breaks = 0:1,
                    labels = c("No snow", "Snow"),
                    name = "") +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "left", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())   +  labs(title =  "")

```


Plot the chm

```{r, echo=FALSE}

veg_all_gunni <- raster('data/Gunnison__chm_2point1by1point6.tif')

chm_study_area_open_large<- crop(veg_all_gunni,aoi_manu)
plot(chm_study_area_open)

chm_large_study_area <- gplot(chm_study_area_open_large)+
 coord_sf(crs = 4326)+
  geom_tile(aes(fill = value))  +
 viridis::scale_fill_viridis(direction = -1, na.value='#FFFFFF00') + 
  theme(panel.background = element_rect(colour = "black", fill="white"),legend.key.size  = unit(12, "mm"),legend.position = "bottom",
      axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x='',  y='', fill="Canopy height (m)") +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())   +  labs(title =  "CHM")

```
Plot  dem open  area

```{r, echo=FALSE}

dem_all_gunni <- raster('data/gunnison_dem3m_wgs84.tif')

dem_study_large_area_open<- crop(dem_all_gunni,aoi_manu)


dem_large_study_area <- gplot(dem_study_large_area_open)+
 coord_sf(crs = 4326)+
  geom_tile(aes(fill = value))  +
 viridis::scale_fill_viridis(direction = -1, na.value='#FFFFFF00') + 
  theme(panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom",legend.key.size  = unit(12, "mm"),
      axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x='',  y='', fill="Elevation (m)") +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())   +  labs(title =  "Elevation")

```

ndvi

```{r , echo=FALSE}
study_large_open_ndvi <- (planet_large_study_area[[4]]-planet_large_study_area[[1]])/(planet_large_study_area[[4]]+planet_large_study_area[[1]])

 study_large_ndvi <- gplot(study_large_open_ndvi)+
 coord_sf(crs = 4326)+
  geom_tile(aes(fill = value))  +
 viridis::scale_fill_viridis(direction = -1, na.value='#FFFFFF00') + 
  theme(panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom", legend.key.size  = unit(12, "mm"),
      axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x='',  y='', fill="NDVI")   +
  theme(text = element_text(size=16) ,panel.background = element_rect(colour = "black", fill="white"),legend.position = "bottom", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())   +  labs(title =  "NDVI")
 
```

```{r , echo=FALSE}
library(patchwork)
layout <- "
ABCD
EFGH
"
 baseplanet_co + base_co +basedemplus_co+ basendvi_co + basechm_co +
     baseslopspnorth_co + basedemco + base_aso_imagery+
  plot_layout(design = layout) +
  plot_annotation(tag_levels = 'A', title = '',
  subtitle = '',
  caption = 'Copyright Planet Labs, Inc. (A)') +
   theme(legend.position = "bottom")
ggsave("figs/main_figure_co_models_scene-forestandplains.png",dpi=300, dev='png',  height=12, width=14,units="in")
```

```{r , echo=FALSE}
library(patchwork)
layout <- "
ABCD
EFGH
#IJK
"
 baseplanet_co + base_co +basedemplus_co+ basendvi_co + basechm_co +
     baseslopspnorth_co + basedemco + base_aso_imagery+
   study_large_ndvi+ chm_large_study_area + dem_large_study_area+
  plot_layout(design = layout,guides = 'collect') +
  plot_annotation(tag_levels = 'A', title = '',
  subtitle = '',
  caption = 'Copyright Planet Labs, Inc. (A)') +
   theme(legend.position = "bottom")
ggsave("figs/main_figure_co_models_scene-forestandplains_revised.png",dpi=300, dev='png',  height=12, width=14,units="in")
```


```{r , echo=FALSE}
library(patchwork)

 baseplanet_co + base_aso_imagery+ baseext_co +  basendvi_co +
  plot_annotation(
  caption = 'Copyright Planet Labs, Inc.')
ggsave("figs/topthree-forestandplains.png",dpi=300, dev='png',  height=12, width=18,units="in")
```

calcylate area
```{r , echo=FALSE}

```
